# Generated by Django 5.0.6 on 2024-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_date', models.DateTimeField()),
                ('dentist_time', models.TimeField()),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.dentist')),
            ],
        ),
    ]
