# Generated by Django 5.0.6 on 2024-06-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.dentisttime'),
        ),
    ]
