# Generated by Django 5.0.6 on 2024-06-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('dentist', 'dentist_time')},
        ),
    ]
